In [2]:
import numpy as np

# NumPy
Матрицы - частный случай n-мерного массива. Такие массивы предоставляет пакет *NumPy*, (`np` – традиционный псведоним для импорта). Они гораздо быстрее питоновских списков, потому что размещают их подряд в непрерывной области памяти. Все элементы np.array имеют один и тот же тип `dtype`. 

In [26]:
# Пример — матрица 2x3
A = np.array([[3,1,2], [4,0,2]])
A

array([[3, 1, 2],
       [4, 0, 2]])

In [27]:
# явно укажем тип данных
A = np.array([[3,1,2], [4,0,2]], dtype=np.float32)
A

array([[3., 1., 2.],
       [4., 0., 2.]], dtype=float32)

### Изменение формы
Форму и размерность массива можно менять, не изменяя данные

In [28]:
A.shape

(2, 3)

In [30]:
A.reshape(3,2)

array([[3., 1.],
       [2., 4.],
       [0., 2.]], dtype=float32)

In [17]:
w = np.array([3,2,1])
w

array([3, 2, 1])

In [18]:
u = np.array([3,2,1]).reshape((3,1))
u

array([[3],
       [2],
       [1]])

In [19]:
v = np.array([4,2,-4]).reshape((1,3))
v

array([[ 4,  2, -4]])

### Произведения

In [15]:
u*v

array([[ 12,   6, -12],
       [  8,   4,  -8],
       [  4,   2,  -4]])

In [16]:
v.dot(u)

array([[12]])

In [20]:
v.dot(w)

array([12])

In [29]:
A.dot(w)

array([13., 14.])

### Разница во времени
Векторизованные через NumPy операции гораздо быстрее, чем итерирование через циклы в питоне, так как внутри данные массива расположены линейно в памяти, и используется один питоновский вызов к эффективному алгоритму на Си.

Рассмотрим пример: подсчитаем среднее арифметическое значения 3x+5y для N пар (x,y)

In [35]:
from random import randint
N = 1000000
A = [(randint(1,99), randint(1,99)) for i in range(N)]
A

[(52, 46),
 (81, 68),
 (67, 34),
 (62, 20),
 (43, 4),
 (1, 55),
 (80, 16),
 (12, 37),
 (49, 43),
 (84, 41),
 (9, 93),
 (5, 77),
 (73, 36),
 (80, 56),
 (3, 89),
 (44, 15),
 (99, 12),
 (14, 24),
 (55, 51),
 (54, 26),
 (27, 96),
 (27, 47),
 (50, 24),
 (40, 54),
 (95, 95),
 (24, 43),
 (40, 10),
 (46, 16),
 (35, 46),
 (67, 54),
 (11, 81),
 (21, 26),
 (83, 68),
 (39, 87),
 (94, 8),
 (73, 88),
 (12, 67),
 (93, 39),
 (22, 63),
 (88, 13),
 (70, 87),
 (69, 15),
 (96, 72),
 (58, 91),
 (59, 29),
 (62, 43),
 (43, 69),
 (76, 68),
 (4, 36),
 (80, 15),
 (33, 62),
 (34, 11),
 (76, 77),
 (68, 81),
 (79, 60),
 (53, 28),
 (14, 3),
 (95, 21),
 (4, 31),
 (19, 90),
 (51, 60),
 (12, 96),
 (33, 36),
 (98, 55),
 (10, 87),
 (46, 78),
 (79, 42),
 (15, 85),
 (95, 1),
 (83, 86),
 (49, 35),
 (16, 63),
 (69, 67),
 (29, 39),
 (2, 61),
 (10, 48),
 (19, 90),
 (21, 80),
 (24, 27),
 (33, 45),
 (8, 73),
 (14, 77),
 (91, 22),
 (19, 9),
 (5, 8),
 (30, 47),
 (52, 95),
 (73, 48),
 (7, 17),
 (2, 89),
 (64, 8),
 (52, 57),
 (77, 

In [36]:
S = 0
for x,y in A:
    S += 3*x+5*y
S/N

399.998291

In [37]:
def avg3x5y(A):
    S = 0
    for x,y in A:
        S += 3*x+5*y
    return S/N

%timeit avg3x5y(A)

146 ms ± 2.73 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [44]:
A_ = np.array(A)
B = np.array([3,5])
%timeit A_.dot(B).mean()

12.9 ms ± 57.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
